--
title: "ADSP WGS GWAS results"
author: "Xulong Wang"
date: "May 3, 2016"
output: pdf_document
---

```{r, eval = F}

setwd("/data/xwang/adsp3/glm")
setwd("/data/xwang/adsp3/glm2") # Binary

glm <- lapply(dir(), function(x) { load(x); fit })
lrt <- lapply(glm, function(x) {y = x[, "lp"]; y = y - min(y); names(y) = rownames(x); y})

glm <- as.data.frame(do.call(rbind, glm))
glm$P <- pnorm(abs(glm$p), sd = glm$se, lower.tail = F) * 2

#---

setwd("/data/xwang/adsp3/sampling")
setwd("/data/xwang/adsp3/sampling2") # Binary
setwd("/data/xwang/adsp3/sampling_prior") # Prior

mcmc <- lapply(dir(), function(x) { load(x); fit })
mcmc <- lapply(mcmc, function(x) { lapply(x, function(y) { sapply(y[all(! grepl("Error", y))], function(z) z["p", ]) }) })

mcmc <- lapply(mcmc, function(x) do.call(cbind, x))
mcmc <- t(do.call(cbind, mcmc[sapply(mcmc, function(x) dim(x)[1]) == 10]))

mcmc <- as.data.frame(mcmc)
mcmc$P <- pnorm(abs(unlist(mcmc$mean)), sd = unlist(mcmc$sd), lower.tail = F) * 2

save(mcmc, file = "~/Dropbox/GitHub/wgs/gwas/sampling.rdt")
save(mcmc, file = "~/Dropbox/GitHub/wgs/gwas/sampling_prior.rdt")

setwd("/data/xwang/adsp3/R")
geno = lapply(1:22, function(x) { cat(x, "\n"); load(paste0("chr", x, ".rdt")); geno[rownames(geno) %in% rownames(mcmc), ] })
geno = do.call(rbind, geno)
save(geno, file = "~/Dropbox/GitHub/wgs/gwas/mcmc_geno.rdt")

#---

library(ggplot2)
options(stringsAsFactors = F)

chrlen <- read.delim("~/Dropbox/GitHub/X/genomes/human.hg19.genome", header = F)
chrlen <- chrlen[match(paste0("chr", 1:22), chrlen$V1), ]
chrlen <- cumsum(as.numeric(chrlen$V2)) * 1e-6; names(chrlen) <- c(1:22)
chrmid <- diff(c(0, chrlen)) * 0.5 + c(0, chrlen[-length(chrlen)])

manhattan <- glm
manhattan <- mcmc

manhattan$CHR = as.numeric(gsub(":.*", "", rownames(manhattan)))
manhattan$POS = as.numeric(gsub(".*:(.*)_.*", "\\1", rownames(manhattan)))

manhattan$POS2 <- c(0, chrlen)[manhattan$CHR] + manhattan$POS * 1e-6
manhattan$col <- rep("o", nrow(manhattan))
manhattan$col[manhattan$CHR %% 2 == 1] <- "e"

manhattan$P <- -log10(manhattan$P)

png("~/Dropbox/GitHub/wgs/gwas/manhattan_glm.png", width = 1e3, height = .5e3, res = 100)
png("~/Dropbox/GitHub/wgs/gwas/manhattan_mcmc.png", width = 1e3, height = .5e3, res = 100)
png("~/Dropbox/GitHub/wgs/gwas/manhattan_mcmc_prior.png", width = 1e3, height = .5e3, res = 100)

ggplot(manhattan, aes(x = POS2, y = P, color = col)) + 
  geom_point(alpha = 0.9) + # geom_hline(yintercept = 7.3, color = "gold") +
  scale_x_continuous(breaks = chrmid, labels = names(chrlen)) + ylim(c(0, 9)) + 
  scale_color_manual(values = c("dodgerblue3", "firebrick1")) + 
  theme_bw() + xlab("") + ylab("-log10(P)") + guides(shape = F, color = F) +
  theme(legend.key = element_blank())

dev.off()

```

### Make a table with consequences

```{r}

load("~/Dropbox/GitHub/wgs/gwas/sampling.rdt")
mcmc$UID = gsub(":", "-", gsub("_.*", "", rownames(mcmc)))

load("~/Dropbox/GitHub/wgs/glm/vep.rdt")
vep$UID = gsub(":", "-", gsub("-.*", "", vep$Location))

vep[vep$Consequence == "missense_variant", ]
unique(vep[vep$Consequence == "missense_variant", "SYMBOL"])

gwas = mcmc[mcmc$P < 1e-3, ]
gwas = mcmc[mcmc$P < 1e-4, ]
gwas = mcmc[mcmc$P < 1e-5, ]
gwas = mcmc[mcmc$P < 1e-6, ]
gwas = mcmc[mcmc$P < 5e-8, ]

vep1 = vep[vep$UID %in% gwas$UID, ]

sort(table(vep1$Consequence))
sort(table(vep1$Consequence) / nrow(vep1))
vep1[vep1$Consequence == "missense_variant", ]

gwas$CHR = as.numeric(gsub(":.*", "", rownames(gwas)))
gwas$POS = as.numeric(gsub("^.*:(.*)_.*", "\\1", rownames(gwas)))

grp <- list(); grp[[1]] <- gwas[1, ]; grp_idx <- 1
for (i in 2:nrow(gwas)) {
  chr = gwas$CHR[i] == gwas$CHR[i-1]; pos = gwas$POS[i] - gwas$POS[i-1] < 1e6
  if ( all(chr, pos) ) grp[[grp_idx]] = rbind(grp[[grp_idx]], gwas[i, ])
  else { grp_idx = grp_idx + 1; grp[[grp_idx]] = gwas[i, ] }
}

sapply(grp, nrow)
gwas <- do.call(rbind, lapply(grp, function(x) cbind(PEAK = x$UID[which.min(x$P)], x)))

(peaks = as.character(unique(gwas$PEAK)))

table = cbind(gwas[match(vep1$UID, gwas$UID), ], vep1)
write.xlsx(table, file = "~/Dropbox/GitHub/wgs/gwas/table(20160512).xlsx", sheetName = "P(1e-6)")

intron = vep1[grep("intron", vep1$Consequence), ]
(intron_gene = unique(intron$SYMBOL))

```

# Manuscript Table 1

```{r}

load("~/Dropbox/GitHub/wgs/gwas/sampling.rdt")
table1 = mcmc[mcmc$P < 1e-6, ]
ID = rownames(table1)
table1 = as.data.frame(apply(table1, 2, as.numeric))
rownames(table1) = ID
table1 = table1[order(table1$P), ]
load("/data/xwang/adsp3/meta.rdt")

meta$ID = as.character(meta$ID)
table1 = cbind(meta[match(rownames(table1), meta$ID), ], table1)
write.xlsx(table1, file = "/home/xwang/Dropbox/GitHub/wgs/Manu/Table1.xlsx", sheetName = "P(1e-6)")
save(table1, file = "/home/xwang/Dropbox/GitHub/wgs/Manu/table1.rdt")

```

# Locus plot 

```{r}

source("~/Dropbox/GitHub/wgs/loci/loci200k.R")

lapply(peaks, function(name) {
  pdf(file = paste0("~/Dropbox/GitHub/wgs/loci/loci1e-6/", name, ".pdf"))
  make.locus.200k(name, gwas)
  dev.off()
})

```

#--- Significant variants by MCMC

```{r}

load("~/Dropbox/GitHub/Adsp/new/mdata.rdt")
load("~/Dropbox/GitHub/Adsp/new/mcmc_geno.rdt")

mcmc_geno = x[, mdata$ADSP.Sample.ID]
y = within(mdata, { geno = geno[4, ] })

table(y$AD1, y$geno)
ggplot(y, aes(x = AD1, fill = as.factor(geno))) + geom_bar()

pdf("~/Dropbox/GitHub/Adsp/new/loci.pdf", width = 5, height = 5)
ggplot(y, aes(x = AD1, fill = as.factor(geno))) + 
  geom_bar(position = "fill") + theme_bw() + xlab("") + ylab("Proportion") 
dev.off()

```

### Compare the glmm and glmm_prior (sigma = 0.5)

```{r}

load("~/Dropbox/GitHub/glmm/gwas/glmm_p0.01.rdt")
load("~/Dropbox/GitHub/glmm/gwas/glmm_prior_p0.01.rdt")
load("~/Dropbox/GitHub/glmm/igap/igap.rdt")
load("~/Dropbox/GitHub/glmm/data/glmList.rdt")

glm_old = glmList$gwas[glmList$gwas$LOD > 15,]
glm_old = glm_old[glm_old$CHR %in% c(1:22), ]

table(glm_old$UID %in% rownames(glmm_p0.01))
glm_old$P = pchisq(glm_old$LOD, df = 1, lower.tail = F)

plot(-log10(glm_old$P), -log10(glmm_p0.01[glm_old$UID, "P"]))
cor(-log10(glm_old$P), -log10(glmm_p0.01[glm_old$UID, "P"]), method = "spearman")

glmm = glmm_p0.01[glmm_p0.01$P < 1e-7, ]

uid = rownames(glmm)[rownames(glmm) %in% rownames(glmm_prior_p0.01)]
glmm[uid, ]
glmm_prior_p0.01[uid, ]

```
